export enum ConversationState {
  NORMAL_MESSAGE = 0,
  FIRST_CONVERSATION = 1,
  MEMBER_JOINED_OPEN_CHATROOM = 2,
  MEMBER_LEFT_OPEN_CHATROOM = 3,
  MEMBER_ADDED_TO_CHATROOM = 7,
  MEMBER_LEFT_SECRET_CHATROOM = 8,
  MEMBER_REMOVED_FROM_CHATROOM = 9,
  POLL = 10,
  ALL_MEMBERS_ADDED = 11,
  TOPIC_CHANGED = 12,
}
