export enum TokenValues {
  LOCAL_ACCESS_TOKEN = "LOCAL_ACCESS_TOKEN",
  LOCAL_REFRESH_TOKEN = "LOCAL_REFRESH_TOKEN",
  LOCAL_USER = "LOCAL_USER",
  LOCAL_API_KEY = "LOCAL_API_KEY",
  IS_USER_ONBOARDING_DONE = "IS_USER_ONBOARDING_DONE",
  SEEN_POST = "SEEN_POST",
  TEMPORARY_POST = "TEMPORARY_POST"
}
